data:
  data_dir: "data/raw/"
  train_images_file: "train-images-idx3-ubyte"
  train_labels_file: "train-labels-idx1-ubyte"
  test_images_file: "t10k-images-idx3-ubyte"
  test_labels_file: "t10k-labels-idx1-ubyte"

model:
  batch_size: 128
  epochs: 80
  learning_rate: 0.0008
  weight_decay: 0.01
  device: "cpu"

  scheduler:
    name: "CosineAnnealingLR"

    min_lr: 1.0e-6

    CosineAnnealingLR:
      last_epoch: -1

    ReduceLROnPlateau:
      mode: "max"
      factor: 0.1               # the coefficient of `learning_rate` reduction
      patience: 3               # max epochs before reducing `learning_rate`
      verbose: True             # whether print changes of `learning_rate`

  early_stopping:
    patience: 15              # max epochs before stopping training
    min_delta: 0.0001         # min reduction in `loss`, considered an improvement

output:
  checkpoint_dir: "outputs/checkpoints/"
  log_dir: "outputs/logs/"
  result_dir: "outputs/predictions/"
  model_save_name: "Fashion_MNIST_model"
